name: Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      # - name: Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the fonts
        run: for i in times.ttf simhei.ttf simkai.ttf simsun.ttc simsunb.ttf simfang.ttf; do wget -P fonts/ https://xugr.keybase.pub/static/fonts/$i; done
      
      - name: Copy the fonts # In newer version of fontconfig, it reads $HOME/.local/share/fonts/ but not $HOME/.fonts
        run: mkdir -p ~/.local/share/fonts && cp -r fonts/* ~/.local/share/fonts/
      
      - name: Build font information caches
        run: fc-cache -rv

      - name: Install TexLive and make
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
            make clean

      - name: Prepare files for gh-pages
        run: |
          mkdir public
          mv main.pdf public/main.pdf


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true